my_string = input('Как ваше самочувствие? ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print('Чтоб всегда', my_string)
print('Чтоб всегда'.replace(' ',''))
print(my_string[0:1])
print(my_string[-1])
